// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockTraderBroker.DB;

namespace StockTraderBroker.Migrations
{
    [DbContext(typeof(StockTraderBrokerContext))]
    [Migration("20190321220443_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StockTraderBroker.DB.BuyRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("AccountId");

                    b.Property<int>("AmountOfShares");

                    b.Property<double>("Price");

                    b.Property<Guid>("ReserveId");

                    b.Property<long>("StockId");

                    b.Property<DateTime>("TimeOut");

                    b.HasKey("Id");

                    b.ToTable("BuyRequests");
                });

            modelBuilder.Entity("StockTraderBroker.DB.SellRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("AccountId");

                    b.Property<int>("AmountOfShares");

                    b.Property<double>("Price");

                    b.Property<long>("StockId");

                    b.Property<DateTime>("TimeOut");

                    b.HasKey("Id");

                    b.ToTable("SellRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
